title: Ersan Efe Oğuz
markdown: kramdown

# for atom feed
author:
  name: Ersan Efe Oğuz
  email: ersanefe21@gmail.com

plugins:
  - jemoji
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

collections_dir: all_collections
collections:
  posts:
    output: true
collections:
  projects:
    output: true
    permalink: /blog/:name/

defaults:
  - scope:
      path: "_posts"
    values:
      layout: "post"
      permalink: /posts/:title/
exclude: ["sitemap.xml", "feed.xml", "LICENSE", "README.md"]
